version: "3.8"

services:
  andcool_site:
    container_name: andcool_site
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    networks:
      - nginx
    environment:
      - TZ=Europe/Moscow

networks:
  nginx:
    external: true
    name: nginx
